export default {
  SET_USER: 'SET_USER',
  SET_SOCKET: 'SET_SOCKET',
  SET_CHAT_LIST: 'SET_CHAT_LIST',
  SET_CHAT_LIST_DETAIL: 'SET_CHAT_LIST_DETAIL',
  SET_MASS_LIST: 'SET_MASS_LIST',
  SET_SYS_MSG: 'SET_SYS_MSG',
  SET_EXPERT_MSG: 'SET_EXPERT_MSG',
  SET_STORAGE_REF: 'SET_STORAGE_REF'
}